name: Build release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run build
        run: |
          make
          zip mpv_thumbnail.zip mpv_thumbnail_script_server.lua mpv_thumbnail_script_client_osc.lua
          gh release create v$GITHUB_RUN_NUMBER mpv_thumbnail.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
